### PR TITLE
Add support for Mongoid v7

### LINKED ISSUE #9: Add support for mongoid 7

### PR DESCRIPTION
**Pull request by joeyAghion**
Fixes #9.

### CODE REVIEW

**Comment by dblock** [comment]
README/CHANGELOG please.

**Comment by dblock** [comment]
Better, but still need travis.yml and Gemfile explicitly for 7.

**Comment by joeyAghion** [comment]
But don't we require `HEAD` if we want to install `7.0.0.beta`?

Or are you advising we add _both_ `HEAD` and `7` options, with both [for now] installing directly from github's `mongodb/mongodb` repo?

**Comment by dblock** [comment]
This looks great, I added you to collaborators, feel free to merge on 💚

**Comment by joeyAghion** [comment]
FYI I added separate spec "matrix" entries for `7` and `HEAD`, though they do the same thing now.

Build is green, but I don't have write access. Care to merge or grant me that?

**Comment by dblock** [comment]
I invited you to the project @joeyAghion

**Comment by joeyAghion** [comment]
Thanks and sorry--didn't realize I had to accept that.

**Pull request merged**
